### ISSUE TITLE
how i fix it?

### ISSUE THREAD

**Issue by vrochacaio** [dieselpoint/norm#49]
`    public List<House> getAll(){
        return this.database.sql("SELECT * FROM `tb_house`").results(House.class);
    }
`

[21:40:54 ERROR]: Error occurred while enabling FirmaCore v1.0.0 (Is it up to date?)
com.dieselpoint.norm.DbException: java.lang.InstantiationException: br.firmacore.controllers.house.DAO.models.House
        at com.dieselpoint.norm.Query.results(Query.java:216) ~[?:?]
        at com.dieselpoint.norm.Database.results(Database.java:162) ~[?:?]
        at br.firmacore.controllers.house.DAO.HouseRepository.getAll(HouseRepository.java:25) ~[?:?]
        at br.firmacore.controllers.house.HouseController.<init>(HouseController.java:21) ~[?:?]
        at br.firmacore.Main.onEnable(Main.java:20) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:884) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.Bukkit.reload(Bukkit.java:654) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714) ~[patched_1.15.2.jar:git-Paper-196]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-196]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-196]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164) ~[patched_1.15.2.jar:git-Paper-196]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-196]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.InstantiationException: br.firmacore.controllers.house.DAO.models.House
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_251]
        at com.dieselpoint.norm.Query.results(Query.java:203) ~[?:?]
        ... 20 more
Caused by: java.lang.NoSuchMethodException: br.firmacore.controllers.house.DAO.models.House.<init>()
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_251]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_251]
        at com.dieselpoint.norm.Query.results(Query.java:203) ~[?:?]
        ... 20 more

**Comment by vrochacaio** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
