### ISSUE TITLE
The custom converter is not working

### ISSUE THREAD

**Issue by Xmonpl** [dieselpoint/norm#64]
Hey, custom object serialization is not working for me, can somebody help me?

Code
```java
  database.createTable(Ticket.class);
  final Ticket ticket = Ticket.builder()
          .topic("test")
          .priority("LOW")
          .user_id("1")
          .message("test")
          .color(Color.ORANGE)
          .build();
  database.insert(ticket);
  System.out.println(database.sql("SELECT * FROM `tickets` WHERE `id` = ?", 1).first(Ticket.class).toString());
 ```
 
 
Error
```
Exception in thread "main" com.dieselpoint.norm.DbException: Could not write value into pojo. Property: color method: public void org.eu.xmon.customerpanel.object.Ticket.setColor(java.awt.Color) value: java.awt.Color[r=255,g=200,b=0] value class: class java.lang.String
	at com.dieselpoint.norm.sqlmakers.StandardPojoInfo.putValue(StandardPojoInfo.java:304)
	at com.dieselpoint.norm.Query.results(Query.java:213)
	at com.dieselpoint.norm.Query.first(Query.java:101)
	at org.eu.xmon.customerpanel.database.DbConnect.connect(DbConnect.java:43)
	at org.eu.xmon.customerpanel.Bootstrap.main(Bootstrap.java:12)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.dieselpoint.norm.sqlmakers.StandardPojoInfo.putValue(StandardPojoInfo.java:300)
	... 4 more

Process finished with exit code 1
```

Ticket Object
```java
@Data
@Builder
@ToString
@AllArgsConstructor
@RequiredArgsConstructor
@Table(name = "tickets")
public class Ticket {
    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    @Basic
    @Column(name = "id", nullable = false, unique = true)
    public Integer id;

    @Column(name = "userid")
    private String user_id;

    @Column(name = "priority")
    private String priority;

    @Column(name = "topic")
    private String topic;

    @Column(name = "message")
    private String message;

    @Column
    @Convert(converter = ColorConverter.class)
    private Color color;

}
```

ColorConverter from the example given in readme

```java
@Converter
public class ColorConverter implements AttributeConverter<Color, String> {

    private static final String SEPARATOR = "\\|";

    /**
     * Convert Color object to a String
     * with format red|green|blue|alpha
     */
    @Override
    public String convertToDatabaseColumn(Color color) {
        StringBuilder sb = new StringBuilder();
        sb.append(color.getRed()).append(SEPARATOR)
                .append(color.getGreen())
                .append(SEPARATOR)
                .append(color.getBlue())
                .append(SEPARATOR)
                .append(color.getAlpha());
        return sb.toString();
    }

    /**
     * Convert a String with format red|green|blue|alpha
     * to a Color object
     */
    @Override
    public Color convertToEntityAttribute(String colorString) {
        String[] rgb = colorString.split(SEPARATOR);
        return new Color(Integer.parseInt(rgb[0]),
                Integer.parseInt(rgb[1]),
                Integer.parseInt(rgb[2]),
                Integer.parseInt(rgb[3]));
    }

}
```

**Comment by ccleve** [comment]
I do not see an error in your code. This is a puzzler.

Can you put some breakpoints in your code and step through it? In particular, I'd check to see if your Converter is really getting invoked. The error message says that you're calling setColor() with a String, which would happen if the converter weren't there.

Also, make sure you're using a recent version.

**Comment by Xmonpl** [comment]
The converter does not run at all, I set up a simple System.out.println at the beginning convertToDatabaseColumn and convertToEntityAttribute and neither was displayed in the console.

Yes, i have the latest version.

```
<dependency>
    <groupId>com.dieselpoint</groupId>
    <artifactId>norm</artifactId>
    <version>1.0.4</version>
</dependency>
```

**Comment by ccleve** [comment]
I wrote a test case and figured it out. You need to make the fields in Ticket public. 

```
@Column
@Convert(converter = ColorConverter.class)
public Color color;

```

**Comment by Xmonpl** [comment]
oh okey, i try it

**Comment by Xmonpl** [comment]
Thanks for help, now it works 👯

**Comment by ccleve** [comment]
Weird, I've hit another bug in the converter code itself. It has to do with parsing the color string. Easily fixed, though, and nothing to do with norm.
