### ISSUE TITLE
How can I get norm to work properly in a minecraft-plugin

### ISSUE THREAD

**Issue by mrmrmystery** [dieselpoint/norm#82]
Hi, I tried to use norm with a Sqlite database.

I found out, that you have to change something in the HikariConfig here: https://github.com/dieselpoint/norm/issues/12
When I added this to my code, the database connected. But whenever I try to query something in the database, for example `db.sql("SELECT * FROM track").results(Track.class).get(0);`, I get an "NoSuchMethodError".

Edit:
I first thought it was because of slite. I tried it with mysql but it still didn't work. I think it's because of the minecraft plugin but I don't know why

Here the stacktrace:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'boatrace' in plugin BoatRace v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.dieselpoint.norm.DbException: java.lang.NoSuchMethodException: de.swc.game.Track.<init>()
	at com.dieselpoint.norm.Query.results(Query.java:228) ~[swc-1.0-SNAPSHOT.jar:?]
	at de.swc.commands.subcmds.AddCheckpointCommand.onCommand(AddCheckpointCommand.java:50) ~[swc-1.0-SNAPSHOT.jar:?]
	at de.swc.commands.BoatRaceCommand.onCommand(BoatRaceCommand.java:37) ~[swc-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.NoSuchMethodException: de.swc.game.Track.<init>()
	at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at com.dieselpoint.norm.Query.results(Query.java:214) ~[swc-1.0-SNAPSHOT.jar:?]
	at de.swc.commands.subcmds.AddCheckpointCommand.onCommand(AddCheckpointCommand.java:50) ~[swc-1.0-SNAPSHOT.jar:?]
	at de.swc.commands.BoatRaceCommand.onCommand(BoatRaceCommand.java:37) ~[swc-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by ccleve** [comment]
Make sure that your de.swc.game.Track class has a zero-arg constructor. Remember, norm has to construct an instance of this class for each row it's returning. It won't know how to construct the class if the only constructors available require arguments.

**Comment by mrmrmystery** [comment]
Yes, that fixed it! thanks!
